### ISSUE TITLE
game crashes evertime i press alt tab

### ISSUE THREAD

**Issue by zazp** [nacrt/SkyblockClient#2]
ok so i just downloaded this and i usually do alt tab to switch between windows and when i did it my game crashed for some reason then when i reloaded the client and did alt tab again it crashed again other than that the client is very nice

**Comment by nacrt** [comment]
I've heard of this issue before...
Can you upload a crash log?
.minecraft/skyclient/crash-reports

**Comment by joel-alvarado** [comment]
Same issue here, alt tab crashes not only SkyClient, but the entire OS for a few minutes before the client forces itself to close, at which point a few seconds later everything goes back to normal. There is no crash-reports folder in the SkyClient directory, but I did find the [latestlog](https://github.com/nacrt/SkyblockClient/files/6339886/latest.log) file of the session which crashed.

**Comment by nacrt** [comment]
this doesn't tell me a lot. sorry.
i recommend you join https://discord.gg/sk1er
they are experts when it comes to 1.8.9 bugs
