### ISSUE TITLE
Can't use this

### ISSUE THREAD

**Issue by LeapedExplore** [nacrt/SkyblockClient#3]
I just really want to use this but the only thing is that i am on mac so therefor i can not use the file so if you could make it also work for mac it would really help

**Comment by electron271** [comment]
same issue with compatibility, would like linux release

**Comment by JoeyE2** [comment]
both of you, join the discords of the mods in skyclient inducing the skyclient discord. leadexplore check https://github.com/nacrt/Skyblock-Client-Mac electron again join the discords of the people who made the mods including skyclient discord and download all the mods and if you really want a skyclient experience ask for the custom main menu mod.

**Comment by nacrt** [comment]
mac support is in the works, please be a little more patient
