### ISSUE TITLE
1.3.10 isint on realeses tab -joey

### ISSUE THREAD

**Issue by JoeyE2** [nacrt/SkyblockClient#4]
put 1.3.10 on realeses tab thanks

**Comment by JoeyE2** [comment]
just kidding sorry :wat:

**Comment by electron271** [comment]
https://guides.github.com/activities/hello-world/

**Comment by JoeyE2** [comment]
w h a t

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
